### ISSUE TITLE
text tool problem

### ISSUE THREAD

**Issue by donaldlee2008** [imagej/imagej1#43] opened 2017-09-14 00:36 UTC
1. text tool can not accept any Chinese or Japanese,   English is good.

2.  text tool  configure has some encode problem . please see  screen shot link
https://pan.baidu.com/s/1jIehyUa

Imagej version 1.51p  
 java1.8
windows 10 Professional  simple chinense

**Comment by imagejan** [comment] 2017-09-14 05:36
The text tool was not developed to support non-ascii characters. You should be able to work around this using the `drawString` macro function, see also [this discussion](http://forum.imagej.net/t/how-can-i-type-or-paste-chinese-charaters-to-image-directly/2421?u=imagejan) on the forum.

**Comment by imagejan** [comment] 2019-10-31 15:06
Duplicate of #22.

**Closed by imagejan** 2019-10-31 15:06 UTC
