### ISSUE TITLE
Convolver class on floating point image data 

### ISSUE THREAD

**Issue by erexhepa** [imagej/imagej1#12] opened 2016-04-03 13:34 UTC
Hi,

We are working on a plugin for ImageJ and while using some of the built-in classes of ImageJ I found an issue with the class ij/plugin/filter/Convolver.java. What I was trying to do is to apply a 2D convolution with a 2D filter and I was calling the method convolveFloat from the class Convolver.java. However it doesn't perform the convolution as it try to get get a ROI from the image if the image doesn't have a ROI defined it doesn't get into the loops performing the convolution. 

It's OK if you run it from the ImageJ interface because it goes through a roiReset and set's the ROI to to the entire image. However if you instantiate a Convolver object from inside another class you need to call roiReset before. I guess it is useful to keep the ROI in case you want to run the convolution in a specific ROI but maybe if there is no ROI the reset should be done automatically or indicate it in method documentation that the user should do it.

 Elton

**Comment by rasband** [comment] 2016-04-04 03:56
Hi Elton,

Please provide a minimal script or plugin that reproduces this problem. The convolveFloat() method calls the ImageProcessor.getRoi() method, which should return an ROI corresponding to the the entire image if an ROI has not been defined.

-wayne

**Comment by erexhepa** [comment] 2016-04-04 07:32
Hi,

Yeah you're right it doest that but the returned ROI has x,y = (0,0) with width 0. 

Let me prepare a plugin to reproduce the problem.

Elton

**Comment by erexhepa** [comment] 2016-04-04 15:28
Hi,

Here is the plugin calling the Convolver class. I copied it locally to and modified it to be able to run it but I added a test functionality in the plugin to reproduce the error with the original IJ Convolver.java

https://github.com/erexhepa/IJ_PROJECTION_PLUGIN/blob/master/IJ2/SME_PROJECTION_ENS_SRC.jar

It should appear under Plugin directory under "SME Plugin" -> SME Plugin ENS :: Debug and testing

you need to load the stack below before running it: 

https://github.com/erexhepa/IJ_PROJECTION_PLUGIN/blob/master/IJ2/Cell_border1.tif

the lines where the call to Convoler.java are in 

SME_ENS_Sml_TEST:65-68

**Comment by rasband** [comment] 2016-04-05 01:19
This bug is fixed in the latest ImageJ daily build (1.51a2). The FloatProcessor(int[][]) constructor was not correctly initializing the ROI. You can work around the bug by replacing

   ip2 = new FloatProcessor(ip.duplicate().getIntArray());

with

   ip2 = ip.convertToFloat();

Here is minimal JavaScript code that reproduces the bug:

  img = IJ.createImage("a", "8-bit random", 500, 500, 2);
  stack = img.getStack();
  stack2 = new ImageStack(img.getWidth(),img.getHeight());
  kernel = [1,1,1,1,1,1,1,1,1];
  convolver = new Convolver();
  for (i=1; i<=stack.getSize(); i++) {
    ip = stack.getProcessor(i);
    ip2 = new FloatProcessor(ip.duplicate().getIntArray());
    //ip2 = ip.convertToFloat();
    if (ip2.getRoi().width==0)
       IJ.error("Empty ROI: "+ip2.getRoi());
    convolver.convolveFloat(ip2, kernel, 3, 3);
    stack2.addSlice(ip2)
  }
  img2 = new ImagePlus("b",stack2);
  img2.show();

**Comment by erexhepa** [comment] 2016-04-05 05:33
Hi, 

Thanks for the clarifications. I was indeed working with an earlier build. Your solution does fix the problem.

Elton

**Closed** 2016-04-13 11:48 UTC

**Comment by rasband** [comment] 2017-12-29 16:34
> On Dec 28, 2017, at 3:19 PM, Aryeh Weiss <aryeh@cc.huji.ac.il> wrote:
> 
> [snip]
> 
> As an aside - on my system Fiji takes a huge amount of time to
> load, and sometimes I have to launch it a few times. When I launch it using the debug alias, it seems to get stuck at

This may be because ImageJ 1.51s does not display the main window until after running the AutoRun (in StartupMacros) and RunAtStartup (created by Edit>Options>Startup) macros. You can work around this problem by upgrading to ImageJ 1.51t, which runs these macros on a separate thread. Unlike earlier versions of ImageJ, ImageJ 1.51t runs the AutoRun and RunAtStartup macros on the same thread so they to not interfere with each other.

-wayne
