### ISSUE TITLE
ChannelSplitter creating a non-correct ImageStack object

### ISSUE THREAD

**Issue by biocompibens** [imagej/imagej1#16] opened 2016-06-03 07:13 UTC
Hi,

I was debugging a plugin for ImageJ we are writing and I found a possible problem with both ImageStack and ChannelSplitter classes. 

The problem we have in the plugin is that we have hyper-stack (color-stack) that we want to process. We call ChannelSplitter to separate the colors into individual stacks so that we can process them. The problem is that at this point a getVoxel on the stack will return 0 for every pixel. 

I had a look and it looks like ChannelSplitter creates ImageStacks objects with the type property set to -1 (UNDEFINED) although it should be byte. The getVoxel method check the type property and returns 0 all the time if the type is -1. Shouldn't an error be thrown at this point ? You get a zero and you do not realize what is going on. 

I managed to make it work in my dev environment by changing the setType method of ImageStack from private to public and calling this after the channel splitting. This method would set the type accordingly to the bitdepth. Doing this fixes the issue but involves editing ImageStack. 

Would you have any other suggestions ?

Elton

**Comment by ctrueden** [comment] 2016-06-03 13:17
@rasband may respond with a fix here, but FYI: it is possible to call private methods of a class using Java's reflection API. In this case, you would write something like this (untested):
```java
final Method setType = ImageStack.class.getDeclaredMethod("setType", new Object[] {Object.class});
setType.setAccessible(true);
setType.invoke(myImageStack, new byte[0]);
```
At least that way, you don't have to hack the ImageJ code itself, which makes your workaround more maintainable.

**Comment by rasband** [comment] 2016-06-03 17:44
Could you please provide a minimal script or plugin that reproduces this problem, preferable one that uses one of the sample images, such as the Mitosis hyperstack. I was not able to reproduce this problem using the Image>Color>Split Channels command and the Mitosis hyperstack, even after first converting it to to 8-bit and RGB.

**Comment by rasband** [comment] 2016-06-03 17:59
I found a way to reproduce this problem so I no longer need a test script or plugin.

**Comment by rasband** [comment] 2016-06-03 18:21
This bug is fixed in the latest ImageJ daily build (1.51b26). The ImageStack.setPixels() method was not setting the type.

**Comment by erexhepa** [comment] 2016-06-03 18:51
Thanks wayne. I was about to send you the link.

The suggestion from @ctrueden worked too with a some slight modifications

`Object pixVal = images[i].getStack().getPixels(1);
            Method setType = images[i].getStack().getClass().getDeclaredMethod("setType", Object.class);
            setType.setAccessible(true);
            try {
                setType.invoke(images[i].getStack(), pixVal);
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }`

**Comment by erexhepa** [comment] 2016-06-03 19:18
we will go with the fix above (some of the user who will test the plugin will not have the latest build) but it is a dangerous solution if the method signature change in a future upgrade. 

Thanks again for the feedback.

**Closed** 2017-03-16 18:56 UTC
