### ISSUE TITLE
Support open image url ends with `.jpeg` instead of `.jpg`

### ISSUE THREAD

**Issue by oeway** [imagej/imagej1#108] opened 2021-02-14 18:27 UTC
Right now, it seems ImageJ only recognize image url ends with `.jpg`, but sometimes the url can be `.jpeg`, would be nice to support both.

**Comment by rasband** [comment] 2021-02-14 20:07
This fix is in the ImageJ 1.53h9 daily build but I was not able to reproduce the problem on MacOS using this test script

```
   imp = IJ.openImage("http://wsr.imagej.net/images/leaf.jpeg");
   imp.show();
```

**Closed by rasband** 2021-02-14 20:07 UTC
